stages:
  - test

run_tests:
  stage: test
  tags:
    - shell

  before_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt

  script:
    - source .venv/bin/activate
    - export HTTP_PROXY=http://172.28.64.1:10809
    - export HTTPS_PROXY=http://172.28.64.1:10809
    - export http_proxy=$HTTP_PROXY
    - export https_proxy=$HTTPS_PROXY
    - export NO_PROXY=jsonplaceholder.typicode.com
    - export no_proxy=jsonplaceholder.typicode.com
    - pytest -v --qase-mode=testops